# Generated by Django 3.0.3 on 2020-02-21 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
    ]
