# Generated by Django 3.0.3 on 2020-02-24 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0003_film_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_review',
            name='session_key',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
