# Generated by Django 3.0.3 on 2020-02-24 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_film_genre_is_active'),
        ('film_list', '0004_film_review_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_list',
            name='film_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='films.Film'),
        ),
        migrations.AddField(
            model_name='film_review',
            name='film',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='films.Film'),
        ),
    ]
