# Generated by Django 3.0.3 on 2020-02-24 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0005_auto_20200224_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film_review',
            name='status',
        ),
        migrations.AddField(
            model_name='film_review',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
