# Generated by Django 3.0.3 on 2020-02-24 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0007_auto_20200224_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_review',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
