# Generated by Django 3.0.3 on 2020-02-25 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0008_film_review_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='film_review',
            name='film_list',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='film_list.Film_list'),
        ),
    ]
