# Generated by Django 3.0.3 on 2020-02-25 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film_list', '0010_film_list_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film_list',
            old_name='list_email',
            new_name='user_email',
        ),
        migrations.RenameField(
            model_name='film_list',
            old_name='list_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='film_list',
            name='list_comments',
        ),
    ]
